# Generated by Django 5.2.5 on 2025-08-21 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_personas', models.PositiveIntegerField(default=1, help_text='Para áreas como Terraza o Alberca')),
                ('cantidad_espacios', models.PositiveIntegerField(default=1, help_text='Para áreas con múltiples espacios idénticos (ej. Estacionamientos)')),
            ],
        ),
        migrations.CreateModel(
            name='ContadorFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_folio', models.PositiveIntegerField(default=1999)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.CharField(max_length=10)),
                ('propietario', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('estatus_condominio', models.CharField(choices=[('Al Corriente', 'Al Corriente'), ('Con Adeudo', 'Con Adeudo'), ('En Convenio', 'En Convenio de Pago')], default='Al Corriente', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.villa')),
            ],
            options={
                'unique_together': {('villa', 'numero_casa')},
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(default='Mantenimiento Mensual', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Atrasado', 'Atrasado'), ('En Verificación', 'En Verificación')], default='Pendiente', max_length=20)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('es_deuda_anterior', models.BooleanField(default=False, help_text='Marcar si este pago es anterior a Junio 2025')),
                ('folio', models.PositiveIntegerField(blank=True, help_text='Número de folio del recibo', null=True, unique=True)),
                ('recibo_pdf', models.FileField(blank=True, help_text='PDF del recibo generado', null=True, upload_to='recibos/')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.casa')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('cantidad_personas', models.PositiveIntegerField(blank=True, help_text='Número de invitados (si aplica)', null=True)),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.areacomun')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.casa')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Matrícula del vehículo', max_length=10, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('tarjeta_rfid', models.CharField(blank=True, help_text='ID único de la tarjeta de acceso', max_length=50, null=True, unique=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Aprobación'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='condominio.casa')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.marca')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.modelo')),
            ],
        ),
        migrations.AddField(
            model_name='areacomun',
            name='villa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.villa'),
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=100)),
                ('token_acceso', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('foto_identificacion', models.ImageField(blank=True, null=True, upload_to='identificaciones/')),
                ('foto_placas', models.ImageField(blank=True, null=True, upload_to='placas/')),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('Esperando', 'Esperando'), ('Adentro', 'Adentro'), ('Completada', 'Completada')], default='Esperando', max_length=20)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.casa')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='areacomun',
            unique_together={('villa', 'nombre')},
        ),
    ]
