# Generated by Django 5.2.5 on 2025-08-22 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0003_villa_google_maps_link_villa_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='fecha_hora_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='fecha_hora_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='guardia_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservaciones_devueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='guardia_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservaciones_entregadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitante',
            name='fecha_hora_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='fecha_hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='guardia_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes_ingresados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitante',
            name='guardia_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes_salida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('En Uso', 'En Uso'), ('Completada', 'Completada')], default='Pendiente', max_length=20),
        ),
    ]
