# Generated by Django 5.2.5 on 2025-08-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_reservacion_fecha_hora_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='tipo_residente',
            field=models.CharField(choices=[('Propietario', 'Propietario'), ('Arrendatario', 'Arrendatario')], default='Propietario', max_length=20),
        ),
    ]
