# Generated by Django 5.2.5 on 2025-08-23 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0005_casa_tipo_residente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Explica detalladamente la propuesta.')),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('beneficios', models.TextField(help_text='Describe los beneficios para la comunidad.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin_votacion', models.DateTimeField(blank=True, help_text='El administrador establece esta fecha al aprobar.', null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Aprobación'), ('Activa', 'Activa para Votar'), ('Aprobada', 'Resultado: Aprobada'), ('Rechazada', 'Resultado: Rechazada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('autor', models.ForeignKey(help_text='Casa que origina la propuesta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.casa')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.villa')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('A Favor', 'A Favor'), ('En Contra', 'En Contra'), ('Abstencion', 'Abstención')], max_length=10)),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.casa')),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='condominio.propuesta')),
            ],
            options={
                'unique_together': {('propuesta', 'casa')},
            },
        ),
    ]
