# Generated by Django 5.2.5 on 2025-09-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0010_casa_saldo_transaccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaccion",
            name="recibo_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="recibos_transacciones/"
            ),
        ),
    ]
