# Generated by Django 5.2.5 on 2025-11-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0011_transaccion_recibo_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="CasaConAdeudo",
            fields=[],
            options={
                "verbose_name": "Casa con Adeudo",
                "verbose_name_plural": "Casas con Adeudo",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("condominio.casa",),
        ),
    ]
