# Generated by Django 5.2.5 on 2025-12-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0013_categoriaincidencia_reporteincidencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenciaReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.ImageField(upload_to="evidencias_incidencias/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="condominio.reporteincidencia",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        help_text="Vecino que aportó esta evidencia extra",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="condominio.casa",
                    ),
                ),
            ],
        ),
    ]
