# Generated by Django 5.2.5 on 2025-12-05 06:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0015_serviciovecino_reconocimiento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="casa",
            name="inquilino",
            field=models.OneToOneField(
                blank=True,
                help_text="Cuenta secundaria para inquilino o habitante adicional",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="casa_inquilino",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="LugarEstacionamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        choices=[("A", "Lugar A"), ("B", "Lugar B")],
                        help_text="Ej: A o B",
                        max_length=5,
                    ),
                ),
                (
                    "casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lugares",
                        to="condominio.casa",
                    ),
                ),
            ],
            options={
                "unique_together": {("casa", "identificador")},
            },
        ),
        migrations.CreateModel(
            name="DisponibilidadEstacionamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("esta_ocupado_por_dueno", models.BooleanField(default=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lugares_tomados",
                        to="condominio.casa",
                    ),
                ),
                (
                    "lugar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominio.lugarestacionamiento",
                    ),
                ),
            ],
            options={
                "unique_together": {("lugar", "fecha")},
            },
        ),
    ]
