# Generated by Django 5.2.5 on 2025-08-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='fecha_programada',
            field=models.DateTimeField(),
        ),
    ]
