# Generated by Django 5.2.5 on 2025-08-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_alter_visitante_fecha_programada'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Enlace completo de Google Maps', max_length=500),
        ),
        migrations.AddField(
            model_name='villa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_villas/'),
        ),
    ]
