# Generated by Django 5.2.5 on 2025-08-23 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_propuesta_voto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='propuestas_documentos/')),
                ('nombre_documento', models.CharField(blank=True, max_length=100)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='condominio.propuesta')),
            ],
        ),
    ]
