# Generated by Django 5.2.5 on 2025-08-23 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0007_documentopropuesta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(help_text='Ej: Amazon, Mercado Libre, etc.', max_length=100)),
                ('numero_guia', models.CharField(blank=True, help_text='Número de rastreo (opcional)', max_length=100)),
                ('codigo_recogida', models.CharField(blank=True, help_text='Código necesario para recibir el paquete', max_length=50)),
                ('fecha_llegada', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('En Vigilancia', 'En Vigilancia'), ('Entregado', 'Entregado'), ('Esperando Llegada', 'Esperando Llegada')], default='En Vigilancia', max_length=20)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='condominio.casa')),
                ('entregado_a_residente_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_entregados', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
