# Generated by Django 5.2.5 on 2025-09-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0008_paquete"),
    ]

    operations = [
        migrations.AddField(
            model_name="casa",
            name="estado_gafete",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Entregado", "Entregado"),
                    ("En Revision", "En Revisión"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
    ]
