# Generated by Django 5.2.5 on 2025-09-14 16:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0009_casa_estado_gafete"),
    ]

    operations = [
        migrations.AddField(
            model_name="casa",
            name="saldo",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CARGO", "Cargo"),
                            ("ABONO", "Abono"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Siempre un valor positivo. El tipo determina si suma o resta.",
                        max_digits=10,
                    ),
                ),
                ("concepto", models.CharField(max_length=255)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "comprobante",
                    models.ImageField(
                        blank=True, null=True, upload_to="comprobantes_transacciones/"
                    ),
                ),
                (
                    "estado_aprobacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDIENTE", "Pendiente de Aprobación"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="APROBADO",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="condominio.casa",
                    ),
                ),
                (
                    "pago_original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="condominio.pago",
                    ),
                ),
            ],
        ),
    ]
