# Generated by Django 5.2.5 on 2025-12-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0012_casaconadeudo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaIncidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "monto_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=200.0,
                        help_text="Costo de la 1ra multa",
                        max_digits=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReporteIncidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "evidencia_foto",
                    models.ImageField(blank=True, null=True, upload_to="evidencias/"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Revisión"),
                            ("RECHAZADO", "Rechazado / No Procede"),
                            ("MULTA", "Multa Aplicada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("resolucion_admin", models.TextField(blank=True)),
                (
                    "monto_multa",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "casa_infractora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_recibidos",
                        to="condominio.casa",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="condominio.categoriaincidencia",
                    ),
                ),
                (
                    "reportante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_realizados",
                        to="condominio.casa",
                    ),
                ),
                (
                    "transaccion",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="condominio.transaccion",
                    ),
                ),
            ],
        ),
    ]
