# Generated by Django 5.2.5 on 2025-12-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0014_evidenciareporte"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicioVecino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ej: Plomería García o Postres Caseros",
                        max_length=100,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            (
                                "Oficio",
                                "🛠️ Oficio / Reparaciones (Plomero, Electricista...)",
                            ),
                            ("Comida", "🍔 Comida / Postres"),
                            ("Producto", "📦 Venta de Productos (Catálogo, Ropa...)"),
                            (
                                "Profesional",
                                "immo Servicios Profesionales (Contador, Abogado...)",
                            ),
                            ("Clases", "🎓 Clases / Enseñanza"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(help_text="Describe qué haces, horarios, etc."),
                ),
                (
                    "telefono_contacto",
                    models.CharField(help_text="Número para WhatsApp", max_length=15),
                ),
                (
                    "imagen_promo",
                    models.ImageField(
                        blank=True, null=True, upload_to="servicios_vecinos/"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                (
                    "casa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mi_servicio",
                        to="condominio.casa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reconocimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Conocido", "👋 Lo conozco / Buen vecino"),
                            ("Recomendado", "⭐ Recomiendo su servicio"),
                            ("Ayuda", "🤝 Me ha ayudado en algo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "otorgado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconocimientos_dados",
                        to="condominio.casa",
                    ),
                ),
                (
                    "recibido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconocimientos_recibidos",
                        to="condominio.casa",
                    ),
                ),
            ],
            options={
                "unique_together": {("otorgado_por", "recibido_por")},
            },
        ),
    ]
