# Generated by Django 5.2.5 on 2025-12-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0016_casa_inquilino_lugarestacionamiento_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lugarestacionamiento",
            options={
                "verbose_name": "Lugar de Estacionamiento",
                "verbose_name_plural": "Lugares de Estacionamiento",
            },
        ),
        migrations.AlterUniqueTogether(
            name="lugarestacionamiento",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lugarestacionamiento",
            name="es_publico",
            field=models.BooleanField(
                default=False,
                help_text="Marcar True si es un cajón de uso común/visitas",
            ),
        ),
        migrations.AddField(
            model_name="lugarestacionamiento",
            name="ocupado_actualmente_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lugar_en_uso",
                to="condominio.casa",
            ),
        ),
        migrations.AlterField(
            model_name="lugarestacionamiento",
            name="casa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lugares_propiedad",
                to="condominio.casa",
            ),
        ),
        migrations.AlterField(
            model_name="lugarestacionamiento",
            name="identificador",
            field=models.CharField(
                help_text="Ej: A, B, o V1, V2 para visitas", max_length=10
            ),
        ),
        migrations.CreateModel(
            name="ReservaEstacionamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("placa_vehiculo", models.CharField(max_length=15)),
                ("modelo_vehiculo", models.CharField(blank=True, max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Aprobación (>24h)"),
                            ("CONFIRMADA", "Confirmada"),
                            ("ACTIVA", "En Uso Actualmente"),
                            ("FINALIZADA", "Finalizada"),
                            ("RECHAZADA", "Rechazada"),
                            ("EN_REVISION_EVENTO", "Solicitado mover por Evento"),
                        ],
                        default="CONFIRMADA",
                        max_length=25,
                    ),
                ),
                ("requiere_aprobacion_admin", models.BooleanField(default=False)),
                (
                    "motivo_rechazo",
                    models.TextField(
                        blank=True,
                        help_text="Razón si el admin rechaza la reserva larga",
                        null=True,
                    ),
                ),
                (
                    "notificado_por_evento",
                    models.BooleanField(
                        default=False, help_text="Si se le avisó que debe mover el auto"
                    ),
                ),
                (
                    "causa_mayor_reportada",
                    models.BooleanField(
                        default=False,
                        help_text="El vecino indicó que NO puede moverlo (causa mayor)",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "casa_solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas_estacionamiento",
                        to="condominio.casa",
                    ),
                ),
                (
                    "lugar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="condominio.lugarestacionamiento",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DisponibilidadEstacionamiento",
        ),
    ]
