# Generated by Django 5.2.5 on 2025-12-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0017_alter_lugarestacionamiento_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisponibilidadEstacionamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                (
                    "lugar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidades",
                        to="condominio.lugarestacionamiento",
                    ),
                ),
                (
                    "publicado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominio.casa",
                    ),
                ),
            ],
        ),
    ]
